# Generated by Django 2.0.3 on 2019-04-23 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190416_0105'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='client_from',
        ),
        migrations.AddField(
            model_name='ticket',
            name='client_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Client'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='doctor_to',
        ),
        migrations.AddField(
            model_name='ticket',
            name='doctor_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Doctor'),
        ),
    ]
