# Generated by Django 2.2 on 2020-05-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190425_0242'),
        ('main', '0002_auto_20190424_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Waiting', 'Waiting'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Waiting', max_length=15, null=True)),
                ('client_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Client')),
                ('doctor_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Doctor')),
            ],
        ),
    ]
